package com.mycompany.myapp;


import com.codename1.db.Database;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.mycompany.gui.SignInForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    public Resources theme;
     public static Database myDataBase;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");
        
        
        
          try {
            myDataBase = Database.openOrCreate("esprit.db");
            System.out.println(myDataBase);
            System.out.println("test database");
            myDataBase.execute("CREATE TABLE IF NOT EXISTS Product (id INTEGER AUTO INCREMENT PRIMARY KEY, "
                    + "ProductName TEXT, Description TEXT, image TEXT ,Reference TEXT,Price INTEGER,Stock INTEGER) ");
            System.out.println("test after database");
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
       /* if(current != null){
            current.show();
            return;
        }*/
        //houni awl interface yet7al
        //new StatistiquePieForm(theme).show(); //n7oto signup bch yjibha awl form
        new SignInForm(theme).show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
