<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWupveNY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWupveNY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWupveNY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWupveNY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWupveNY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WupveNY',
    'container.build_id' => '2027e60b',
    'container.build_time' => 1645956669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWupveNY');
