<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIOQx33K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIOQx33K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIOQx33K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIOQx33K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIOQx33K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IOQx33K',
    'container.build_id' => 'efaa6218',
    'container.build_time' => 1645466456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIOQx33K');
