<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6wIExme\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6wIExme/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6wIExme.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6wIExme\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6wIExme\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6wIExme',
    'container.build_id' => '78936140',
    'container.build_time' => 1646225851,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6wIExme');
